### ISSUE TITLE
ATT&CK Navigator layer is not working

### ISSUE THREAD

**Issue by gifrate** [scythe-io/community-threats#69]
I get an error when trying to load the layer into the navigator by pasting URL.

**Comment by jorgeorchilles** [comment]
For which threat are you having trouble loading the ATT&CK Navigator layer? You can do it one of two ways:

- Download the raw JSON to your file system and "Open Existing Layer" from "Upload from local"
- Load from URL - ensure you click the raw button in GitHub to get the raw JSON, should look like this: https://raw.githubusercontent.com/scythe-io/community-threats/master/Hive/Hive_ATT%26CK_Navigator.json

You can also replace the #LayerURL in this URL with the raw one you want to open: https://mitre-attack.github.io/attack-navigator/#layerURL=https://raw.githubusercontent.com/scythe-io/community-threats/master/Hive/Hive_ATT%26CK_Navigator.json

**Comment by gifrate** [comment]
I am trying to open the one for Lazarus.

I have tried both copying the URL to the Navigator Website and downloading locally and uploading to Navigator.

It may be an issue with versioning or JSON formatting.

**Comment by jorgeorchilles** [comment]
That is correct, it was generated before ATT&CK Navigator version 4.3 and ATT&CK v9. Just click okay and Yes when opening the URL: 

https://mitre-attack.github.io/attack-navigator/#layerURL=https://raw.githubusercontent.com/scythe-io/community-threats/master/Lazarus/Lazarus_ATTACK_Navigator.json

Should show:
![image](https://user-images.githubusercontent.com/52384511/132371129-13ba0829-c597-4930-b363-ee46569ca4f8.png)

**Comment by gifrate** [comment]
It does work when I use the url you provided, thanks.

**Comment by jorgeorchilles** [comment]
Great!
